# Base URL
@fitlife_planner_back_end_HostAddress = http://localhost:5000

### Get user by userId
GET {{fitlife_planner_back_end_HostAddress}}/account?userId=dba363cb-1a5b-402c-99cf-90cb7e05d438
Accept: application/json

### Create a new user
POST {{fitlife_planner_back_end_HostAddress}}/account
Content-Type: application/json
Accept: application/json

{
  "email": "test21111@example.com",
  "password": "0123456",
  "username": "chessy1603"
}



### AuthenticationController
### Login user
POST {{fitlife_planner_back_end_HostAddress}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test2@example.com",
  "password": "0123456"
}

### AuthenticationController
### Refresh token
POST {{fitlife_planner_back_end_HostAddress}}/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken" : "7c53657e-2113-4262-baa1-9fd15de0e851",
  "userId" : "2ce23af5-996f-48a7-9414-2775225f7550",
  "userName": "chessy1603"
} 



