services:
  fitlife-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitlife-backend
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    restart: always
